// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wskawnzfojtmwvwyhemx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indza2F3bnpmb2p0bXd2d3loZW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzgwMTYsImV4cCI6MjA2NzY1NDAxNn0.gV7vpoVf4ZPg3PTajLl-IxBeigtQDCsvBeMWTQDX7bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});